ARG REGISTRY_SERVER
ARG REGISTRY_USER
ARG REGISTRY_PASSWORD
ARG IMAGE_NAME
ARG IMAGE_TAG
FROM maven as builder

# run unit-test and build binary
COPY pom.xml /usr/src/mymaven/pom.xml
COPY Dockerfile /usr/src/mymaven/Dockerfile
ADD src/ /usr/src/mymaven/src

WORKDIR /usr/src/mymaven/
RUN mvn clean test
RUN mvn clean package




#Run Static code Analysis
FROM newtmitch/sonar-scanner as sonarqube
WORKDIR /usr/src
COPY ./sonar-project.properties /usr/lib/sonar-scanner/conf/sonar-scanner.properties
COPY --from=builder /usr/src/mymaven/src ./
RUN sonar-scanner -Dsonar.projectBaseDir=/usr/src


# Build image and push to registry using Buildah
FROM buildah as imageBuild
ARG REGISTRY_SERVER
ARG IMAGE_NAME
ARG IMAGE_TAG
ARG REGISTRY_USER
ARG REGISTRY_PASSWORD
WORKDIR /usr/src/app

COPY --from=builder /usr/src/mymaven/src/target/*.jar ./
WORKDIR /usr/src
COPY  --from builder /usr/src/mymaven/src/Dockerfile ./
RUN buildah bud -t ${REGISTRY_SERVER}/${IMAGE_NAME}:${IMAGE_NAME}
RUN push ${REGISTRY_SERVER}/${IMAGE_NAME}:${IMAGE_NAME}

# Scan for created container image' vulnerabilities with policy, needs a running anchore-engine instance
#ANCHORE_CLI_URL=http://myserver.example.com:8228/v1
#ANCHORE_CLI_USER=admin
#ANCHORE_CLI_PASS=foobar
#ANCHORE_CLI_SSL_VERIFY=n

FROM anchore/anchore-engine:v1.1.0
ARG REGISTRY_SERVER
ARG IMAGE_NAME
ARG IMAGE_TAG
ARG REGISTRY_USER
ARG REGISTRY_PASSWORD

cp policy-vuln-up-to-medium.json /path/to/policy/policy-vuln-up-to-medium.json
RUN anchore-cli policy add /path/to/policy/policy-vuln-up-to-medium.json
    && anchore-cli policy list | grep -v Policy | awk '{print $1}' | xargs -i anchore-cli policy activate {}
    && anchore-cli evaluate check ${REGISTRY_SERVER}/${IMAGE_NAME}:${IMAGE_NAME}
    && anchore-cli image vuln ${REGISTRY_SERVER}/${IMAGE_NAME}:${IMAGE_NAME} all
    && anchore-cli evaluate check ${REGISTRY_SERVER}/${IMAGE_NAME}:${IMAGE_NAME}
